{% set version = '4.9-5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-meta
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/meta_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/meta/meta_{{ version }}.tar.gz
  sha256: 8361d2ab0d86e726cbbd57942efe2abb4907fd930261e389acdf1ad5e15468fa

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-lme4
    - r-metafor >=1.9_9
  run:
    - r-base
    - r-lme4
    - r-metafor >=1.9_9

test:
  commands:
    - $R -e "library('meta')"           # [not win]
    - "\"%R%\" -e \"library('meta')\""  # [win]

about:
  home: https://github.com/guido-s/meta http://meta-analysis-with-r.org
  license: GPL (>= 2)
  summary: "User-friendly general package providing standard methods for meta-analysis and supporting
    Schwarzer, Carpenter, and R\xC3\xBCcker <DOI:10.1007/978-3-319-21416-0>, \"Meta-Analysis
    with R\" (2015): - fixed effect and random effects meta-analysis; - several plots
    (forest, funnel, Galbraith / radial, L'Abbe, Baujat, bubble); - statistical tests
    and trim-and-fill method to evaluate bias in meta-analysis; - import data from 'RevMan
    5'; - prediction interval, Hartung-Knapp and Paule-Mandel method for random effects
    model; - cumulative meta-analysis and leave-one-out meta-analysis; - meta-regression;
    - generalised linear mixed models; - produce forest plot summarising several (subgroup)
    meta-analyses."
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - slacalle

# Package: meta
# Title: General Package for Meta-Analysis
# Version: 4.9-5
# Date: 2019-04-11
# Depends: R (>= 2.9.1)
# Imports: grid, metafor (>= 1.9-9), lme4
# Suggests: numDeriv, BiasedUrn
# Authors@R: person("Guido", "Schwarzer", role = c("cre", "aut"), email = "sc@imbi.uni-freiburg.de", comment = c(ORCID = "0000-0001-6214-9087"))
# URL: https://github.com/guido-s/meta http://meta-analysis-with-r.org
# Description: User-friendly general package providing standard methods for meta-analysis and supporting Schwarzer, Carpenter, and RA14cker <DOI:10.1007/978-3-319-21416-0>, "Meta-Analysis with R" (2015): - fixed effect and random effects meta-analysis; - several plots (forest, funnel, Galbraith / radial, L'Abbe, Baujat, bubble); - statistical tests and trim-and-fill method to evaluate bias in meta-analysis; - import data from 'RevMan 5'; - prediction interval, Hartung-Knapp and Paule-Mandel method for random effects model; - cumulative meta-analysis and leave-one-out meta-analysis; - meta-regression; - generalised linear mixed models; - produce forest plot summarising several (subgroup) meta-analyses.
# License: GPL (>= 2)
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-04-11 16:23:08 UTC; sc
# Author: Guido Schwarzer [cre, aut] (<https://orcid.org/0000-0001-6214-9087>)
# Maintainer: Guido Schwarzer <sc@imbi.uni-freiburg.de>
# Repository: CRAN
# Date/Publication: 2019-04-11 17:32:41 UTC
