{% set version = "8.0-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-meta
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/meta_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/meta/meta_{{ version }}.tar.gz
  sha256: 4453dbb45873dac74a561be04e57fe4c40398abeb0a533e1f9ae5202d8c2a726

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-compquadform
    - r-dplyr
    - r-lme4
    - r-magrittr
    - r-metadat
    - r-metafor >=3.0_0
    - r-purrr
    - r-readr
    - r-stringr
    - r-xml2
  run:
    - r-base
    - r-compquadform
    - r-dplyr
    - r-lme4
    - r-magrittr
    - r-metadat
    - r-metafor >=3.0_0
    - r-purrr
    - r-readr
    - r-stringr
    - r-xml2

test:
  commands:
    - $R -e "library('meta')"           # [not win]
    - "\"%R%\" -e \"library('meta')\""  # [win]

about:
  home: https://github.com/guido-s/meta http://meta-analysis-with-r.org
  license: GPL-2.0-or-later
  summary: "User-friendly general package providing standard methods for meta-analysis and supporting Schwarzer, Carpenter, and Rücker <DOI:10.1007/978-3-319-21416-0>, \"Meta-Analysis with R\" (2015): - fixed effect and random effects meta-analysis; - several plots (forest, funnel, Galbraith / radial, L'Abbe, Baujat, bubble);
    - statistical tests and trim-and-fill method to evaluate bias in meta-analysis; - import data from 'RevMan 5'; - prediction interval, Hartung-Knapp and Paule-Mandel method for random effects model; - cumulative meta-analysis and leave-one-out meta-analysis; - meta-regression; - generalised linear mixed models; - produce
    forest plot summarising several (subgroup) meta-analyses."
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - slacalle

# Package: meta
# Title: General Package for Meta-Analysis
# Version: 4.9-9
# Date: 2019-12-19
# Depends: R (>= 2.9.1)
# Imports: grid, metafor (>= 2.1-0), lme4, CompQuadForm
# Suggests: BiasedUrn
# Authors@R: person("Guido", "Schwarzer", role = c("cre", "aut"), email = "sc@imbi.uni-freiburg.de", comment = c(ORCID = "0000-0001-6214-9087"))
# URL: https://github.com/guido-s/meta http://meta-analysis-with-r.org
# Description: User-friendly general package providing standard methods for meta-analysis and supporting Schwarzer, Carpenter, and Rucker <DOI:10.1007/978-3-319-21416-0>, "Meta-Analysis with R" (2015): - fixed effect and random effects meta-analysis; - several plots (forest, funnel, Galbraith / radial, L'Abbe, Baujat, bubble); - statistical tests and trim-and-fill method to evaluate bias in meta-analysis; - import data from 'RevMan 5'; - prediction interval, Hartung-Knapp and Paule-Mandel method for random effects model; - cumulative meta-analysis and leave-one-out meta-analysis; - meta-regression; - generalised linear mixed models; - produce forest plot summarising several (subgroup) meta-analyses.
# License: GPL (>= 2)
# Encoding: UTF-8
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2019-12-19 09:17:08 UTC; sc
# Author: Guido Schwarzer [cre, aut] (<https://orcid.org/0000-0001-6214-9087>)
# Maintainer: Guido Schwarzer <sc@imbi.uni-freiburg.de>
# Repository: CRAN
# Date/Publication: 2019-12-19 14:00:04 UTC
