# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qsJuH3JfMlz3Hzc6q7N5IsbSxXob4cmoxql6JRIgX84KXXipKuMoUCWc2HmusIfDdbpRj+ooKFVNW9WC5BDRAPxq7OEl8uDqvvI/ja815N0qcRSCiaZYptxJj64xZzedyy4VyBsQ1kRxQblYdzlFfiToO24WxkUBg+ln6HcpmdBol10RFDBzf6kfOW31klwz1bn2SC2daJcX3m2iEQqcazsymb630ZDgrB+R33XObhsQQZWRyFtiPmXiRQfD7uCnOXFo5tjCbjYxEponjCAfP9kQD4KadiOvo20BrIJBiOHqR2zPJr/P6sS0Dm4F2O0QWmwKS4LaxLtGkvVY1cRxyABkXCWEWuJ61qQ0WDYwxqVbn8oePkCujv89D+ALcVLaXj+trEPgnsd2kS2WV4mMN8jU5m1M3UDkQjCzcfRc7WMcG2dqjma5/trmXYTzAkUS3/eZKX6B/1a6O1waRdWZ5WKKhqxb0f1ACPD4Kde16Ic1f4zCO+K8NSAGOH8uPAg0j0hAso0YCVPgCKaxq+HyGidVKuq+OqQZVHUdTdMy7mNT+ZkYxAHcNfYMn4rmgpggdUXm6+USV8HRC6Xv97scfz5EffsxraunbvwDImJCI5LCAXul8EHRMWI04nq1SAXfRToOiNAGLYp6pcg+xbj7lzqwUrTmnDkw9qiQO+UBGHI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
