travis:
  secure:
    BINSTAR_TOKEN: V4jIoSbnhzBd357Bj/ZmDIcquBIsVEuajz+6w0qZKn8/L9utsfmwwnFlDLn569y9yAzD0XsovbOKXeIW2Kwz9xsXuPZDI7C/P9LiOMfKUEznaudUoMAPwK4oDcSj2NV4XJkOCMQIpnV0QCyRkAoV5bP3XWEmMNhEI8qMcHWDuL2V+w19p8sqfCVqOEa1PeJeHi3PviI1MYbG3IMhM4kxQ024uql5FznedDRd75f78g7oiOyXY3Tv0VsrShX2mVKKmWV3FG7vCkfXKO6CLIP2e2L6/EkSMf0ELTzXbZaEnxKjgRjBfCKMW6TgZZJ0f3kwxx3qhIdfdykHNvCcaLkFBHOzq1NErHuxg+dAJSAhQoxVzsGILcT8RRO81FOFEpv44KD825l1jTM+tbA3+Z+4OwRYK4v8B0xq8GXTcoiLhyI/2TPfiNNhoDQaw1DMM1TH0kVNsF8pJKTL/Vc36g9kEo8o0qouJjtFk9zGaBiliSS0K9iyeRFAhlkCvzNdMOHvKIARUAe67LArNYmY3t/fGpExe1RJqvvj2TPN2kspc99i9JjZWqhGIym8u9zgtJ8Lq+dnFz6XzUMkcAbUdmOw5VgG9Mf25mMTeuzlIm/oXn2MmKr4jAeDn0DyyMEROTF4r5ORjzTdpNesGet5boErIR7cc1YGc1pmgGB+vUXvBEg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
