travis:
  secure:
    BINSTAR_TOKEN: buUVqdoVcA0U09qdIj8PzIQpMk5Za9nrLObcO2Y+NQvUgrdsqRmsjSPjT4Q4YpZaiDoxH1UXB3fK+J5FFt+OpkKBNjiK+whhIbz8mQhOyg5QmJlDOeDTkex0Z9dvTv6Sak7EXqk98kB87vTeTqZVhz7LE4V4gR1SOGGJoD/48A8ip3h0l0gOJLUkPWLFjMG/OQF3FBY/vZ9Bbtl/hi7bNMb/lx8t80iv105lw80DfxhuO+GKB8DYviv6QgzYD/Fg82GIl7SpnO608c3pDyNiZR3VVBTHtaMmcZBd7g6xc8QiTPtGH7eegunEJ55yi6JzquK5bWjlORqnxFPged2R8TVtWUCy3cDVKdqwjanpZUWR9wLlnUfxy74aAm9YWV51cTp6NPxZn49mAqUGr8tAwZPsJQ+ir0vlOC2hTWAB7Rb7YbRQ2SZVFfN+sSScVwgBopCsiOlJ90IZIHLroNyVNrPDR9eZ2I9HBwo5iKzp+piKTUENnh80hLASBlhXwIAKd9u1PA4Bi4QHAiTZ3Gp5yWHSe2eKwdbH+rvOyBUrlldlmEeh3bgwgAFu6g5ToiaInrnz8uZcX7TUHUamyQ/wnbZA+BaD7fUVLWkLTcT5QCKKweRjWhoVG0sQr+la3J031U9D5+atCeZFsBVvEkVNiMuwNrgISYGED0EseP1e91I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
