travis:
  secure:
    BINSTAR_TOKEN: qV9nIryxJksktl3Ww0RdMw9it/8lnWzY1TIPsfEN9EIhplN/VNwUXN/zbjoT/5+7xI06LtOzghITqUmJaZ/6kuv76P9qsrW9uhnov4oiIFfNnYLTbJNMzE6U9RWz3IcZmKnleScj77sPfRg8Huc+RiHtAmDePd5UWtBRwcwDHFjnga0sfAmcPIzmMj4PK11wMEP0wrhbd7CbSXWgFvn915juqRqEBVWRSZ5Za2TCYP9qkONOqYZ9cqWkJRG7p6aFwoQa1AQBzstCHWKz0s+Y03i30BRIi4dyXotZf04B8BeZqOgrTjd6CO5MTsLr++pMVLWFudB92U44xGG2y1J50rbacKO+qeg80dmqyTPylOfSbqHKh4wt/OVCCNltQnMvkPKdzod1EQn7Ofc30R/LcVAcCT4wV9xcm/lx8gdmYSG0+QwK1ovVznLcNgaDtpRJD6UVqpJOY32Yoj/9+3XkANDJPmlLTotsBWOJWAlkiEscifJe+wrs3QBDk7lRwWRmIABtlDbPlDzsfFv05/afVi9tmumEtBLp/E3tQOKy6/nL9wiW9JhvnVafha4PRpVPgUizvVFs5nVVr28PcIuoBhom/62ZKGBTKRNNnYlpJ63+6fRFukCpI6q0dIYIbs0gKHOpLF3sahCkqoRoVwSSZefIvHwenXc3ZbTuPlnJq+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
