travis:
  secure:
    BINSTAR_TOKEN: CXQ+hyiNhtGnhNN+3xJ0Qo3DgdDkPPARyJpkQMZCnM70unaotNFRMpAQ4bBTe6RAHpjPWBxl9TchU5BTgXOpNy7tloskf404GMi4C7o91aTQEqVEHsMOcQKWEfegwz9V0TngIJux/CwtTrL2inVvp72QWyejUB+LN00Z5eUbeIYgE8G+4l33oHrcVtugiSy66p60vQTzmZzoVTvprC2tS8rAIzZgUow6wdVk76OgMjCQ2ZZpTH4gnpZRioYRjSY7puc1job0qt0o5aMtvMKR0BCofDdYmd0zoORiIKmZ8L8LlaOpdodWLcbY7nbyQBcRwHCiLlDJdPSWdptuqNIj1T+1AZR4fRcy0UdittJ04+CRkP/Sa28Il09Cuc4kUge3l+l59P6jbMo0s8ejgwJGD58VWXnZHVIWm1t+28U+bwGcX2wC60uUB/Jtr+taY/0QMnTRglgErRYomuaX3LEEAeDfyIafCwbmSM8Q1um4UdVHi8vip/tG9smeBWli0LV1py/IjeUWmB9hSpbC2wGtBEMLZMQE+/Uw/fgazFOTxhAgaBMlBDHTpiPpIo0rc/k9dG1qBR1Ta4TDnwhdkc0P+pSAQ5uuaWGnzRK7fbgVxABn59HpEaqFMnmc+zqFITgUCHqUHgkiSkx1S1jE9IjyS6UD33Zc63pvflFcnGhBusA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
