travis:
  secure:
    BINSTAR_TOKEN: W/7YIAarXsnOAWDFfVjxyyOKTtKmOc4TV81qJv2LSdFWE5Q3iAe/0rIgBOBH4sJiv5wdwChyW9fHMYAYU7bLo8fdG3GVhrnig1TU/7rnemnAMorY6Fl+W9M9SOyin+mZC5PNcATtRJJTl0AQDwUWAlI0VP+4Fuv40lkQ04jusqjSZvx2YZXUatgPnXPpxZ4Rx6XHKgj0U07yTHJmJ77U6koQLsiG7SAXwx0H3JsH++suQ5fO1pm4OjmjfehGpvjtjNZapEeqy/p7gHLWLWJ/HzO5UDSjS6LsYw06obF0sZAbzu8lIBVV5sz+MXUFe6wteMGU4KKfzl/v/58oyUjeT+Zw4k3ZWYMQ3+/OEOUF22QZLq/i3xfwpXzBgfSKdyf4lVMilmUNPmqyDo2kE/Tk2IwPHjSh8djT/OLepgne9dpAufOLMMQGGm4CWkCcYK4DUsh/tGl/N/I5KTlR5T3A0U6USsB4bqAs+FFk+wK/HnoAYiQmQ5u4+vXtdlRk+ZvvrA5A/pX+NeFYjh9urEZFELWAzJFLzQHZ74T8d4QPqEB1F9SpB0RErz1e+S8A+0yMrJIpAGhn/G0HBPehJrScUBqeFxXIdQ16XLf+J2WCNp2iVe2lb6UDAmcrq7wXMFZE/ECs72QPlfcX/TNib74eVOG6A/0wKmLt3NWb2ux4aa0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
