travis:
  secure:
    BINSTAR_TOKEN: P8dOpn4hoQADtBLLtnu53G7BWUuXKjjxpxbwMnKKjwwmAr0TCCWrXB9uxUlMIBsg9cHySUm9iqRFUmcqq66O5C0ok91P154JWyrW7E1NMY2OHqOOJtpAYNlgepG5ShsSeJJIhsDEQvDuekPfKAMBn0seEqK0GtHh7Em3CObvdEUnQksDBBMLtTR74tBoOJ860SoNFGc3/cbG27UyK5Wyn79V81M/ju3OJEpvxxqBa7/oolf+Ox5r6hv4kpm8j6RCfbKyxAazDSOj9Su3RZQmPSQ/r4Xdprofl/U7zRszbaA/WrUSFc2ALAttajQjyHQIixB06SuhRwIGo/sFsNJg13lHLYx4zoWx3G6VPRy06sAN78fdbGN1ygY1L8QxYxU45fso8mJEqyXdpTc2Rz0OaFfdO0FIqbWToGgLPVEUxQGnz/XavzPqkm3h2+/ZJ8fwH9PMt3aFfEIxOvvUGIJ6ln55Dd1RsuiqjAAAOoqL61K4Sk2Yx8yNdzWQ3YUnVOavA7E7PxI/M5eD8E9mKyb1ubWROlok8bTaQkmrNPAX840nT6GOtBxFrNsRBsjZTeqWlF7XxGvWT+HHEPXCHArfOQ73o/Ox7fKKQpo+YjpKImicn2w93hP4pnV+l53i6XTXOb+w6Os7MaNKzJ/ZUu617/smg3+rlBpACex+ZXaEDIY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
