travis:
  secure:
    BINSTAR_TOKEN: rvta+1RxlnHI/IZHGE1twn68OdpdZJYuXY39sr3LWWfSNCMFN1D7Go0MdP61FdJItn5Y911U5resKAxclJ+yXVVby8NM25P8o+2wRrHxmOHPzAkBhRXERT5Tj+1b2FCHoz5RKJ8y+5IFmzaxUMVZTJxtJmm7uLwewco/72sxmrWgyT9J/3RjGqLc3NS/xs/r1Wl2z1hx+LwYfLwHWaeRJXrmlxzEnsATdK6AFWrd3PhvrbRZlk9VFtdLt5N3j1WWW8G6iuQ1slIemC/7z24kGTzPqbh//U6fmMcQCkE3bqPXHMvV7gv5sD/ldIMJMWWcpLpwQkltyyPjQoTnoY1T6dEQq1omqTlSNmxSEwdrOb1AbHsWcTB7ucsgMiF+KfpoEmB/eoPop28+rTZ4E6dRddjmmx+m4v8qs9wfV95hj0LhARds08rMHnCHRb67yzJnL+zOIsn6mvzQgKNbTm7jFWF5+h+TXlr2YqZ7gcJz49xwDNs+qsfXDHvGKDray6Dh3jSljqjfYJeXiYjJ198GeNOEkeHcm/VJzaDa8BnBGXt/g7zI/3m0XWNegjtDsELUOqddFoD0SqnkiEaoF6P0HHa6uDunRGi2oUv99OOyIOGir8aWOo4z7b+suXrdEH++tUStY81eeTcLBhhrWtKLsYcJ3ZWiQbC49a20+CyagEw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
