travis:
  secure:
    BINSTAR_TOKEN: G1w8TIfyTqYyqbhNj0KdtF1CBhAmrriSHxxpzM0we0CAV5+AiWNktng5GIWq/wZrIPYynLWba5j6n3vo8PI6YmXsO2MtcLAmcN2lv7yrDqFBw39SiLFJGKej35Pc0awv3yQrcFEZ/3HaUEK/vllGnKBrduTilmQcvOGdjtRDXTx2hbRHp6xZQ4EfCepPPhlCyb+z+INH9Mw28KWMiFhHZr2AdhZW1eq/TfT9ZUmS6QZxY65HVElgIlbwO22UBtpK9IPLYJHK7lTcyVbfFJ6wZICCA6qk2lm9p/GOt82HHytNQKSOBSlbJuTIVIs+6do+sxyA3R//Gy3SIFPxNc3+BeZfkUUcUrp3J983QaXV8jV1nw+ILXP4IyvSNuKAS0t+y7D1v77I+yH8DrT0x3wm3UN9FuMM5YPxbuDdbhGHwla8JGmZBByBSTMEW0gl4K4eLpa6FtVBpsImO0t4v/FQgyxP7RLHlivrhShYdoJq5lAxquRaJF5Nig4jljduAKf8mBr5zv63xWSILqqxLoTqAzPRLfkW4xx8z1ixTspLSyl6f94BzLcrvZ4BpZAj5e7XGAEaJETi9uRfEZCIpCRkwlxkW07IrKlFXX56HZOt86r/IdTGxbcpb63mb7gHdFHW+71W31SQ+iWgyyzUU2JCVs+QOVYLKdY9Y6cU5ftUFS0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
