travis:
  secure:
    BINSTAR_TOKEN: qsJuH3JfMlz3Hzc6q7N5IsbSxXob4cmoxql6JRIgX84KXXipKuMoUCWc2HmusIfDdbpRj+ooKFVNW9WC5BDRAPxq7OEl8uDqvvI/ja815N0qcRSCiaZYptxJj64xZzedyy4VyBsQ1kRxQblYdzlFfiToO24WxkUBg+ln6HcpmdBol10RFDBzf6kfOW31klwz1bn2SC2daJcX3m2iEQqcazsymb630ZDgrB+R33XObhsQQZWRyFtiPmXiRQfD7uCnOXFo5tjCbjYxEponjCAfP9kQD4KadiOvo20BrIJBiOHqR2zPJr/P6sS0Dm4F2O0QWmwKS4LaxLtGkvVY1cRxyABkXCWEWuJ61qQ0WDYwxqVbn8oePkCujv89D+ALcVLaXj+trEPgnsd2kS2WV4mMN8jU5m1M3UDkQjCzcfRc7WMcG2dqjma5/trmXYTzAkUS3/eZKX6B/1a6O1waRdWZ5WKKhqxb0f1ACPD4Kde16Ic1f4zCO+K8NSAGOH8uPAg0j0hAso0YCVPgCKaxq+HyGidVKuq+OqQZVHUdTdMy7mNT+ZkYxAHcNfYMn4rmgpggdUXm6+USV8HRC6Xv97scfz5EffsxraunbvwDImJCI5LCAXul8EHRMWI04nq1SAXfRToOiNAGLYp6pcg+xbj7lzqwUrTmnDkw9qiQO+UBGHI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
