travis:
  secure:
    BINSTAR_TOKEN: gapNACur+g5ztN0tZYBDi+Qc/PhklXknTnk7ORgqkzPUMGxR96KaNkYLVJnykM1Y1MTtFvahwVcOd7ZPlz8M8zMnSzKvSngvZb4pGcj3ADqduxtmpcpupeP+0gf4KYMYU+uS4vusSV0vPfaLs9mbPlxLL5E3ybSXS8VXDcMdby8zeFV7vXAjHoyO45ziAn/WchIWCwv4Nv+VRGxA2Uk7kKqAAQU6rN0NEQRu22n6ac4pirviUY86CIrrAcfkiAc2Qs7HTEUPs6r4SfRpV1UoDIPEdkchP7+FsOZib3JuEYz4EpY09jw4nPwKrWqQtGhvfluHxj1da3kbbAWdnP+3JEwu8PVeWaiLKgNGRdBKebZiDKLwuMjT0ciA9cVTLtaMOTiNsxe4X5r6BVxH3fBYECs298VxVGt/DFacLr2YXIalEITtP60+VY5fJxNWGVYcVnza5/gBtae3EZShHudLYAn6/ZDdg+l3Wv9s18kwxMdfR0Mg4KTNGZnyfYt/bCmHz3R31dNzvHZNPxwhBHuH/S5Y7LmMmbzE7HnidOHv77salmh2B/u2bYVE+yBTWhb9lwhjQeaMZzW/9iQfAfdYWI0lKr8Mrx0StrdTSna2AaVOf9a8kF4xU6wWqdEd/dLcUUPIqpzbLIA+DidIKtNQ71nOu+Oo7pbx2b5BOCnzMpM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
