appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: lvA64N6QsbSEa0D1039oJZ1/F+PKCUfz/MT0BdkV1Z8kqQshvpG96wVMsqvXYKCowi5Ht1wgvf6soicA9snUHkp/oESp06KORHwhsX5l6HtZU2B1T9eldLVS7SXZK16UCZ+C73zauk+6E505w5I6c0kvo1A94A/rGqvpYa+caTe/fRFwNPsVB19z895k69ywXnHsxJuHaHrYuI39RYHaniJ8jRhMQ61c6awciFlophDfMMpjFahgc8bMH/YzE0f5MftubBFVX1xLbmdQBI9GsAecuQ/5a0mpcon5v8+t57zXRZF9nFEoF1pYVdO1IZ352AYHYwuYfBdsdPOOIlp0/5OQulXgXnldVZ9YHEzWBiAJhrtNiwvPBinPrFpP/jrK24G2BbV4vhpms+zJqIGlSuO8QJInBICW7/ckoE3YcmrjHKn6gvFPBun+ip6ySWqMcfcQK3m7JKC++3rfbUBvHZ10Jt9apF5EgDG/aKaqv8cTyNWOXY2rDQnbLnmRIsqKtmABM6eX2G+Zk5hmhBTXOBDJh9MJ0KxG8X2AFpJIBT9a9pO4bii0lqQDtKNmxBvqnt05UmEVkh24pAdNK30wflngQKCtEOU4BF45+ZOto+bRx6iahZVLsujsm7Qph4fb2eBtzBA4Z3p2Dh/PjuzwXBgiEnETZ0Wdhj7UVp9nDjg=}
