travis:
  secure:
    BINSTAR_TOKEN: SacuL4Dv55YLDFmgjHcJVL+RvsqC2y7+6Wu3NWJT4qpiUb1GifDiS1Z5LVGlZ+UNvr5JOom43DAKKfK7+zgeB2yUr+d15dIPdNbsyewWlfltp1Ocl+nTGCKCVgpvJrnKkkBOiT5RxwivsQV/3BALQ5mCzg4fLoc5vdsNpqyosUvJbrLfXCrlOAh2VvvrNKzkyWYhdXzuqTdBeN2lHEhcaNJ76O2rFpxJjdmPHP5aq7ogdltIhKjHSuondAQufzF5CcPZotesoo1nrqDaCs35TKrBo2FZyjTQAD1jchJm1+C6h5+NNBIKtjRVWzH1rE5/M/W3TXGjp0UDtUjx8ta/rw7S9GZbCGKqLNsqzrSDuA9U2uMk17owDS+ZSpokIeY5leu7iwHH8a+M93HQRYdG8zneaBR/SYjus3gQ063Hxwd7NoFWtnXl4SRoFrS8xPazEK1gWayzEIUGIPqGd2EpBBjq6gu3Wf7WfMoLopoO+iDNkAV4W3ASEUALcOWFCwgl18/S54aIFKZ63JApCiw+rpOj5xL3GJhWPPDe91h9Jt1CsoFfSlhQi/y6ALLvr+RtLduEWW2S3N2tgTsD77t/zRX28t7z/Mi4YaUgcf/RlMY1IKLg5yC6CHVA7dsPoyInn2y1ntjfBtDeIuW32C8kYvMaYGCAiu5u8w1cmirSYtM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
