travis:
  secure:
    BINSTAR_TOKEN: NEZ1AXcU8eYIv8eJDi8qTf0tszwyNmNgjMv3d2XdBM2qciSRyTtbs8AjhBD9hYlMN6Hlx4zf1z8p1NsbNzDXwmCMcYQT/IuL2MsgskdVwRJDrP2LkB/cyLpnwFxcvXbpzDtRRYk/Hyu/TJ/3vVJalbLZEcegPKaIAneBm+wiT4rxpPRiRxZqQV6MnQi4Z5LWwHWg3Y+JPb4D5WSRhrotYpn9OP9HURN3w7P/C4/vValkcmcJ2AKcCusNzmhHizYyHp9krIk/Axg0cGm4MhvvTBkbGBoK2BItPfZS7XyXF2yQ5BlOHkiivs8mgY7AfPLQSsy06Jom0Nuym8zceNLrsnbUzzMJME1wOb20N0I4dkzx6JMSNV89ziZPcl49Nav5blAB2zyudHhW+6uMA5ws9stnDDrPtySmBVvx5Fb5AYN5PRtZ4ixcW64CcOpYql2L3+kL3faL/+QcFAdL4Rz+PEHmU4mRp6u496Tt+rIlgtma79vWgjvUEG9+Wn2mlo0AfeIxBi2q5t0+IQ3xTZflafkrwFHNZV6EvwdH0YAT1Yu1/xIYRjyY/0rjJ3h1Pu3xB6byNkNbpfEdAd5zKUUv+o6/PaFe1c4etXJ5GfEoaFqZ3QAEMHfDb8fe2dzgUGVuaCzJMRarFl5mm+qC4E62YU+G4dMBlXcJCsVbSZpwvjs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
