travis:
  secure:
    BINSTAR_TOKEN: rqyOCnVTnAzf2JV7pbG85vuhKjzea0SAJwUcr4oLeMXmRzOdEH8vPmOpxK1fzGI0swHD7zmouMxl2XfmoWK2dL3zpTkrEJ1ZliHCmq9FH8Nzuvzyog/Xab6Ibd5XY1WxWfa90aDU+2RduDNAdqTPJajceq00AbXBdL0HO4FagXGWq0L4AWdF4a4yGhcIEww/GxAZbLS/dDV3XmdKAlwh4cKyqMp9Zr8PxFRbm6orJRbQho0eWbqXa61EYeXWZgJo9hsX2qjOIfoDAfoaOiS0cGfrkofvjG5UaiQwSe0cRav7CY2o1LPffZunNx8YNbCzx1XlLGpsx5M3+oxfV1y/QDsXjscI8ij4/8JXN+5mmSU47N01rHwO7xvfbzCAsTAn355JCN3GchC8CbfNLkQIbdqUfQVBoNyuRfzjxkcMVog/FKhwbn0Nprql2d2z3hDTBQPaMFCBq/nQi1D8a8w8fcysERy1WXMgUUoJ/otpWy8D2zqHV8EKCYjxRsvrkCIL9avcfZMuK3vK5opswyanVofoI9YpEQoSPVKUgOTvsE8Vj9ZlymxNvkCBLP39QhbJG2IJOe7Oz0nNv8dQCtca1t5CgmhLPn4CZd8oMoMMIlMyMNNXTENcYE9bpUDcrOllIs5tbZmm1r87+6hW7x2d2HgHZNeyV3ldbdBUXTIJ6DU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
