travis:
  secure:
    BINSTAR_TOKEN: ErHBA3DWbwGcr6QC1zIMutDpnF1W3+wwDorj2Uw/1gHC801wPxUlPpH1bAK43u4Md1wGPJS0cE5KoukkM1SfWtc4bJXTUPcEKsddWnbCfOS2AvvDqybX4I5ZxneGMaNkus/4gXZTK0ZNE5gkANTDQmGs/OuV4Xg1DaX2RoD7OoPRxrgsFOvkNN4RMmpByKrQC1zD43VCbh4ousgp/HPGhGCW/dP5/ow57pwMAF/MZ8CYcXSFrBrUox0AS1Py6vI4aQsrSmN82/FQlTFzOg8uXWkciScxoehTtLxAUGaPHnOw3NWFEou2vSdq1dN/DxAxBVdyhJp81zB8CGNGeukpbxW2YPQ0ecUNdvOqUfJCOxV96+pxh4Mj/HPKH6/FRf2gjKaD1su99y6n/c/2ishItVKa33nf2ndTBnPRh2hO9tcBvbfGiCdHukdBPh9UtFb4kFy2M25RxBL7zVCsj270J22NKvu+mPqm0rT2rKLM+nL1poRusSH692KSKdog+hBbWgZmCk+TctH6ahwgED0Qr4OR1t89kDPMhhmjDNze2iUJ9O1I/x9uftWJG8NUrQWoHUnzhWLlHBg4VUWIXzr2NCEiW+sFkTmxvG6jMbqSf5Mm8o4fla1r2R5YI9ucqyYDz92ra5iHOSOY9qmk25TQ4Y3EVbnnCeu944jINCZLmiE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
