travis:
  secure:
    BINSTAR_TOKEN: ZRQjsoxgo/ekzcA0W3LBGeM+3sc3ovcY0851xmz3V5giEEZNn5G6apGLkVeBKKh90Zc7tTN9m4uvmetzrA+0W2iXFJ1Q0t/SJwnUz/phts1QOQkjJIdj9FZF9DQgD5wAlhvw5I2RUcd1n9MFoSndUU06C4EKdwOJo48HuqLIQqtRz/3CtKOEHvMDhs8l+XHhRFKZa6ejxnj1CiL7rCUmjhmmTwN6NpvIWBxF1ZnHvab/OIxY9lxz2JWTUCSm9EoGHbDL31Czg0JLSESkST5H1WwCxTndHWukJJ+phgt1E3OhUV7Eev1htpT6lEa/+kQfiW49VBff8EO8afSeNFGhMWoT8fOWRDrAGjHOHCr4qfDASAdxDDogCXIyza8WKLVDh/fpsyxTZ9dhKDpCdmxvxX7alChsSIwBPTFUKTdoMb0c4qkDT1la8ozk246LIPfEx8hsl4cnHKgua27oEXTKFr6OB3S3HGYnA5XBJ63pE+JF2SZ+OvWK1uP/G2y56VJetg0tEcuqFpswwcs+LGq8Yhodb0IIVUMRdFTHllJc2CS+oTNfvjmXCYjQninAqzM53sa31LcA8UfGJNXx5GNkOci5Xohvlg8ocDrdZ1tBEb+AcUQ7DBIMhM77/XqgOa+sXSx4ZIkQwzTtF2mg4KIeg3Ke3VVdl/GlAu08e4i+Jzo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
