travis:
  secure:
    BINSTAR_TOKEN: BtXmHaTUhb700JTSmq4fHTclPeNKs212FBY7ZPe78zdAG7UC3LbN+5Rz/unxqWBrpVvojOKuJfuWgjGLzuQ3P0u3sjqAe5zItbvxGVxyDqWpXk/SKr/Tq6YXe61g6/3hmNJhdKUxXBoGNytDzoBlZQAZfMKjqhG2Ep5SmI8z680GOd/hl0eWDRbHGxgnReYQGKajIVh65HnxpFlTE0JSpbPa6/x78KquzCg57cDZ8qGd0Dwj6bl//uNhi5c/PX5CmyTfYjp172Sb/iKBlmyMgApVMX/XI8MKFi/m1hUeKAlZramv8b4XAIP+AE3VHJ5neKd9Itw8SQTk9EAOOOFyEaGqgdh1OhaxehDeb5Mj2S7osg/oVtF44wPyXn0mauS4inwqlRNHoDxQwrgwwgcpn/PPSpJo+FTsiwJ0hmGv/72npq3iSjUz8zLbjeH/DKel0pvfaEX8YISc3ixskmnzN2a1pGPx6UHYZdbSdvbG6NaRPoamwelA+IhCvxeF9pBZGJUAaFZdup88GhXrbETyGQSIboCytnC+cfMoIq6flhEvBm+4JAAJgZKnqMKDJXEJEM6A2IGssLcsY7sVDCBd6OWmbWXFB5MCTLiB2PkOpT+0/Jr3mI0EzdSpZM4pRLMbgHAJEUEFvoAcOuKTgMLuqzBNhrLToUj65vamXoI7xsE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
